PCB: false
batchsize: 32
color_jitter: false
data_dir: ../Datasets/VeRi_with_plate/pytorch
droprate: 0.5
erasing_p: 0.5
fp16: true
gpu_ids: '0'
lr: 0.05
nclasses: 575
stride: 2
train_all: true
use_NAS: false
use_dense: false
use_ftnet: true
use_siamese: false
warm_epoch: 0
